// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfq3WEFiYEqTof-2VW2M7GQgy-gsxSGWk',
    appId: '1:169730474351:web:b95e987051836f0307689a',
    messagingSenderId: '169730474351',
    projectId: 'mobiefy-flutter-app',
    authDomain: 'mobiefy-flutter-app.firebaseapp.com',
    storageBucket: 'mobiefy-flutter-app.appspot.com',
    measurementId: 'G-LGM3QE24FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9nzHjKwS7CEoGukzH3KXlUUaBGgnzZ3A',
    appId: '1:169730474351:android:17914c91c8a4be1c07689a',
    messagingSenderId: '169730474351',
    projectId: 'mobiefy-flutter-app',
    storageBucket: 'mobiefy-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApn8P92IVojV8r8C9688Jgkz88qwhMTcc',
    appId: '1:169730474351:ios:62253814af5f9a7607689a',
    messagingSenderId: '169730474351',
    projectId: 'mobiefy-flutter-app',
    storageBucket: 'mobiefy-flutter-app.appspot.com',
    iosBundleId: 'com.mobiefy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApn8P92IVojV8r8C9688Jgkz88qwhMTcc',
    appId: '1:169730474351:ios:62253814af5f9a7607689a',
    messagingSenderId: '169730474351',
    projectId: 'mobiefy-flutter-app',
    storageBucket: 'mobiefy-flutter-app.appspot.com',
    iosBundleId: 'com.mobiefy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfq3WEFiYEqTof-2VW2M7GQgy-gsxSGWk',
    appId: '1:169730474351:web:4e7e4c11ea93a49007689a',
    messagingSenderId: '169730474351',
    projectId: 'mobiefy-flutter-app',
    authDomain: 'mobiefy-flutter-app.firebaseapp.com',
    storageBucket: 'mobiefy-flutter-app.appspot.com',
    measurementId: 'G-T3L2RNT4ZD',
  );
}
